# Generated by Django 5.1.2 on 2025-11-25 03:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='datasets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('n_rows', models.PositiveIntegerField(blank=True, null=True)),
                ('n_cols', models.PositiveIntegerField(blank=True, null=True)),
                ('columns_schema', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'En ejecución'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('target_column', models.CharField(max_length=255)),
                ('input_columns', models.JSONField()),
                ('window_size', models.PositiveIntegerField(default=10)),
                ('epochs', models.PositiveIntegerField(default=10)),
                ('loss_final', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('model_path', models.CharField(blank=True, help_text='Ruta en disco del modelo entrenado', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='trainer.dataset')),
            ],
        ),
    ]
