# Generated by Django 5.1.2 on 2025-11-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoSemestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(help_text='Clave de semestre, por ejemplo 2025A, 2024B, etc.', max_length=6, unique=True)),
                ('ingresados', models.PositiveIntegerField(help_text='Número de alumnos de nuevo ingreso en ese semestre')),
            ],
        ),
    ]
