# Generated by Django 5.1.2 on 2025-11-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_ingresosemestral'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='output_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
